easy_admin:
  site_name: 'parts processing'
  user:
    display_name: true
    display_avatar: false
    name_property_path: 'Maxim'
  entities:
    User:
      class: App\Entity\User
      label: 'Users'
      list:
        fields:
          - id
          - firstName
          - lastName
          - email
          - status
      form:
        fields:
          - id
          - firstName
          - lastName
          - email
          - status
    Worker:
      class: App\Entity\Worker
      list:
        fields:
          - id
          - position
          - user
          - qualification
          - { property: 'isQualification',  type: 'boolean' }
          - brigade
          - status
        form:
          fields:
            - id
            - position
            - qualification
            - isQualification
            - property: workerEquipments
              type: 'Symfony\Component\Form\Extension\Core\Type\CollectionType'
#              type: 'choice'
#              type_options:
#                  mapped: false
#                  expanded: true
#                  multiple: true
            - status

    WorkerEquipment:
      class: App\Entity\WorkerEquipment
      list:
        fields:
          - id
          - qualification
          - worker
          - equipment
        form:
          - qualification
          - worker
          - equipment

    Tool:
      class: App\Entity\Tool
      list:
        fields:
          - id
          - name
          - type
          - status
        form:
          - name
          - type
          - status

    TechnolgicalMap:
      class: App\Entity\TechnolgicalMap
      list:
        fields:
          - id
          - name
          - x
          - y
          - z
          - weight
          - materialGrade
          - tolerance
        form:
          - name
          - x
          - y
          - z
          - weight
          - materialGrade
          - tolerance

    Process:
      class: App\Entity\Process
      list:
        fields:
          - time
          - qualification
          - type
          - status
        form:
          - time
          - qualification
          - type
          - status

    Equipment:
      class: App\Entity\Equipment
      list:
        field:
          - accuracy
          - type
          - status
        form:
          - accuracy
          - type
          - status

    Detail:
      class: App\Entity\Detail
      list:
        fields:
          - status
        form:
          - status

    Brigade:
      class: App\Entity\Brigade
      list:
        fields:
          - workShift
          - type
          - status
        form:
          - workShift
          - type
          - status