easy_admin:
  site_name: 'parts processing'
  user:
    display_name: true
    display_avatar: false
    name_property_path: 'Maxim'
  entities:
    User:
      class: App\Entity\User
      label: 'Users'
      list:
        fields:
          - id
          - firstName
          - lastName
          - email
          - status
      form:
        fields:
          - id
          - firstName
          - lastName
          - email
          - status
    Worker:
      class: App\Entity\Worker
      list:
        fields:
          - id
          - position
          - qualification
          - { property: 'isQualification',  type: 'boolean' }
          - status
        form:
          fields:
            - id
            - position
            - qualification
            - isQualification
            - status

          #                    - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
    #                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
    #                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }